### ISSUE TITLE
Support for nested configurations

### ISSUE THREAD

**Issue by lubieniebieski** [netguru/app_konfig#2] opened 2015-07-06 14:31 UTC
it would be very helpful to have nested configuration working, like `AppConfig.emails.office`

**Comment by mic-kul** [comment] 2015-07-06 14:53
:+1:
there is ugly workaround: `AppConfig.emails['office']`

**Comment by nekath** [comment] 2015-07-20 08:19
The problem is that at some keys we get hash instead of OrderedOptions object.

**Comment by nekath** [comment] 2015-09-01 18:58
Fixed in https://github.com/netguru/app_konfig/pull/3

Closing.

**Closed by nekath** 2015-09-01 18:58 UTC
Labels: bug
